export const SET_FILMS = 'SET_FILMS';
export const SET_FILMS_OF_THE_DAY = 'SET_FILMS_OF_THE_DAY';
export const SET_FILTER = 'SET_FILTER';
export const SET_FILTER_VISIBILITY = 'SET_FILTER_VISIBILITY';
export const INCREASE_LOADING = 'INCREASE_LOADING';
export const DECREASE_LOADING = 'DECREASE_LOADING';
